
///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOGENERATED BY GYP_TO_ANDROID.PY. DO NOT EDIT.
//
// This file contains Skia's upstream include/config/SkUserConfig.h as a
// reference, followed by the actual defines set for Android.
//
///////////////////////////////////////////////////////////////////////////////


// Android defines:
#ifndef SkUserConfig_Android_DEFINED
#define SkUserConfig_Android_DEFINED
#ifdef ANDROID
    #include <utils/misc.h>
#endif

#if __BYTE_ORDER == __BIG_ENDIAN
    #define SK_CPU_BENDIAN
    #undef  SK_CPU_LENDIAN
#else
    #define SK_CPU_LENDIAN
    #undef  SK_CPU_BENDIAN
#endif

#define DCT_IFAST_SUPPORTED
#define GR_GL_CUSTOM_SETUP_HEADER "gl/GrGLConfig_chrome.h"
#define GR_GL_USE_NEW_SHADER_SOURCE_SIGNATURE 1
#define QT_NO_KEYWORDS
#define SKIA_DLL
#define SK_ALLOW_STATIC_GLOBAL_INITIALIZERS 0
#define SK_BUILD_FOR_ANDROID
#define SK_BUILD_FOR_ANDROID_FRAMEWORK
#define SK_CAN_USE_DLOPEN 0
#define SK_CODEC_DECODES_RAW
#define SK_DEFAULT_FONT_CACHE_LIMIT   (768 * 1024)
#define SK_DEFAULT_GLOBAL_DISCARDABLE_MEMORY_POOL_SIZE (512 * 1024)
#define SK_FONTHOST_FREETYPE_RUNTIME_VERSION 0x020400
#define SK_FORCE_DISTANCE_FIELD_TEXT 0
#define SK_GAMMA_APPLY_TO_A8
#define SK_GAMMA_CONTRAST 0.0
#define SK_GAMMA_EXPONENT 1.4
#define SK_HAS_GIF_LIBRARY
#define SK_HAS_JPEG_LIBRARY
#define SK_HAS_PNG_LIBRARY
#define SK_HAS_WEBP_LIBRARY
#define SK_IGNORE_ETC1_SUPPORT
#define SK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS
#define SK_INTERNAL
#define SK_PRINT_CODEC_MESSAGES
#define SK_SFNTLY_SUBSETTER "sample/chromium/font_subsetter.h"
#define SK_SUPPORT_GPU 1
#define SK_SUPPORT_LEGACY_CLIPTOLAYERFLAG
#define SK_SUPPORT_LEGACY_COLORFILTER_PTR
#define SK_SUPPORT_LEGACY_CREATESHADER_PTR
#define SK_SUPPORT_LEGACY_DRAWFILTER
#define SK_SUPPORT_LEGACY_GRADIENT_DITHERING
#define SK_SUPPORT_LEGACY_IMAGEFACTORY
#define SK_SUPPORT_LEGACY_MASKFILTER_PTR
#define SK_SUPPORT_LEGACY_MINOR_EFFECT_PTR
#define SK_SUPPORT_LEGACY_NEW_SURFACE_API
#define SK_SUPPORT_LEGACY_PATHEFFECT_PTR
#define SK_SUPPORT_LEGACY_PICTURE_PTR
#define SK_SUPPORT_LEGACY_TYPEFACE_PTR
#define SK_SUPPORT_LEGACY_UNBALANCED_PIXELREF_LOCKCOUNT
#define SK_SUPPORT_LEGACY_XFERMODE_PTR
#define SK_SUPPORT_PDF 1
#define SK_USE_FREETYPE_EMBOLDEN
#define TURBO_HAS_565
#define TURBO_HAS_CROP
#define TURBO_HAS_SKIP

#endif // SkUserConfig_Android_DEFINED
